name: leapfrog-py test

on:
  pull_request:
  push:

jobs:
  run:

    runs-on: ${{ matrix.config.os }}

    name: ${{matrix.config.os }} (${{ matrix.config.py }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   py: '3.12'}
          - {os: ubuntu-latest,  py: '3.9'}
          - {os: ubuntu-latest,  py: '3.10'}
          - {os: ubuntu-latest,  py: '3.11'}
          - {os: ubuntu-latest,  py: '3.12'}
          - {os: windows-latest, py: '3.12'}

    defaults:
      run:
        working-directory: leapfrog-py

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.config.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.py }}

      - name: Extract test data
        shell: bash
        run: ../inst/standalone_model/extract_data

      # We need to install R to run the test to compare R and Python output
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: https://mrc-ide.r-universe.dev
          working-directory: .

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: docopt, local::.
          working-directory: .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Test
        run: |
          hatch run cov-ci

      - name: Lint
        run: |
          # https://github.com/python/mypy/issues/10863
          mkdir -p .mypy_cache
          hatch run lint:all

      - name: Test install
        run: |
          pip install .
          python -c "import leapfrog_py;"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          # This can be useful, but the false positive rate is
          # annoyingly high.
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
